name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run ruff linter
      run: |
        ruff check . --exclude=venv,env,.venv

    - name: Run ruff formatter check
      run: |
        ruff format --check . --exclude=venv,env,.venv

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Set dummy environment variables for tests
      run: |
        echo "IBKR_ACCOUNT_ID=TEST_ACCOUNT" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest -v --tb=short

    - name: Run tests with coverage
      if: matrix.python-version == '3.9'
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage reports
      if: matrix.python-version == '3.9'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      continue-on-error: true
